import "~/styles/globals.css";

import { Flowbite, ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { twMerge } from "tailwind-merge";
import { customTheme } from "./theme";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create App",
  description: "Generated by iamta 0-to1",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <ThemeModeScript />
      </head>
      <body className={twMerge("bg-gray-50 dark:bg-gray-900")}>
        <TRPCReactProvider>
          <Flowbite theme={{ theme: customTheme }}>{children}</Flowbite>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
